name: weather
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio:
  lottie:
  http:
  bloc:
  flutter_bloc:
  animate_do:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/sun.json
    - assets/cloud.json
    - assets/sunny.json
    - assets/mysun.json
    - assets/weatther.json
    - assets/welcome.json
    - assets/h.png
    - assets/temp.png
    - assets/morning.jpg
    - assets/sky.jpg
    - assets/skyy.jpg
    -
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: MadimiOne
      fonts:
        - asset: fonts/MadimiOne-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
